Repository tenzin1308/Nutrimental, pull requests merged in 2022-05, with the labels that each got.

#113 build: user can select dietitian
  client/src/pages/Profile.js
  server/models/userModel.js
  server/routers/userRouter.js
Labels: frontend, backend

#116 fixed the FAQ page
  client/src/pages/FAQ.js
Labels: fix

#118 code cleaning and fixing
  client/src/App.js
  client/src/components/forms/StepTwo.js
Labels: cleanup

#115 Dietitian able to view selected users info
  README.md
  client/src/components/SearchedItem.js
  client/src/components/track/MacroTracker.js
  client/src/pages/Profile.js
  client/src/pages/SignIn.js
  client/src/pages/Tracker.js
  server/routers/userRouter.js
Labels: enhancement, API, frontend, backend

#125 Update MacroTracker.js
  client/src/components/track/MacroTracker.js
Labels: fix
