Repository tenzin1308/Nutrimental, pull requests merged in 2022-01, with the labels that each got.

#2 build: implemented schemas for servers
  server/models/dailyintakeModel.js
  server/models/foodHistory.js
  server/models/userModel.js
  server/models/vitaminModel.js
Labels: build

#5 build: nav bar
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/NavBar.js
Labels: build

#10 fix: adjusted foodhistory and vitamin changes to router and model
  server/models/foodHistoryModel.js
  server/models/vitaminModel.js
  server/routers/vitaminRouter.js
Labels: API, backend

#11 build: server api for dailyintake
  server/models/dailyintakeModel.js
  server/models/foodHistoryModel.js
  server/models/userModel.js
  server/routers/dailyIntakeRouter.js
  server/routers/foodHistoryRouter.js
  server/routers/userRouter.js
Labels: API, backend

#13 build: frontend signup page
  client/src/components/forms/Final.js
  client/src/components/forms/StepOne.js
  client/src/components/forms/StepTwo.js
  client/src/pages/SignUp.js
Labels: enhancement, frontend

#14 fix: added first and last name to user db schema
  server/models/userModel.js
Labels: database, backend

#15 feat: modified UI for signin page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/NavBar.js
  client/src/healthy-food-bg.png
  client/src/healthy-food-bg2.png
  client/src/nutrimental-logo.png
  client/src/pages/SignIn.js
  client/src/pages/SignUp.js
  client/tailwind.config.js
  server/models/userModel.js
Labels: enhancement, frontend

#17 Dante not main
  client/src/UserPool.js
  client/src/components/forms/Final.js
  client/src/components/forms/StepOne.js
  client/src/components/forms/StepTwo.js
  client/src/pages/SignUp.js
Labels: fix

#18 dailyintake router and userrouter done
  server/models/foodHistoryModel.js
  server/routers/foodHistoryRouter.js
Labels: backend

#19 feat: Submit button to submit user inputs to pool
  client/package-lock.json
  client/package.json
  client/src/components/FormErrors.js
  client/src/components/forms/StepTwo.js
  client/src/components/utility/FormValidation.js
Labels: API, frontend

#20 Justin foodhistory db delete
  client/package-lock.json
  client/package.json
  server/package-lock.json
  server/routers/foodHistoryRouter.js
Labels: API, backend

#25 build: profile page
  client/package-lock.json
  client/src/App.js
  client/src/pages/Profile.js
Labels: enhancement, build, frontend

#28 feat: Account layout for account and tracker page implemented
  client/src/App.js
  client/src/components/AccountLayout.js
  client/src/components/InfoContainer.js
  client/src/components/NavBar.js
  client/src/components/Tabs.js
  client/src/pages/AccountInfo.js
  client/src/pages/Dashboard.js
  client/src/pages/Tracker.js
Labels: enhancement, frontend

#29 fix: integrated profile page with accountlayout and fix styling
  client/src/App.js
  client/src/components/AccountLayout.js
  client/src/components/NavBar.js
  client/src/components/Tabs.js
  client/src/pages/AccountInfo.js
  client/src/pages/Profile.js
  client/src/pages/Tracker.js
Labels: frontend, fix

#34 added gender in userModel
  server/models/userModel.js
Labels: backend
