Repository tenzin1308/Nutrimental, pull requests merged in 2022-02, with the labels that each got.

#35 fix: add gender in signup && some housekeeping
  client/src/App.js
  client/src/components/Tabs.js
  client/src/components/forms/StepOne.js
  client/src/components/forms/StepTwo.js
  client/src/pages/Profile.js
  client/src/pages/SignUp.js
  client/src/pages/Tracker.js
Labels: enhancement

#41 Justin search
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/AccountLayout.js
  client/src/components/NavBar.js
  client/src/components/SearchBar.js
  client/src/components/SearchedItem.js
  client/src/pages/Profile.js
  client/src/pages/Searched.js
  server/routers/vitaminRouter.js
Labels: frontend

#46 Tenzin fix searchbar
  .github/workflows/node.js.yml
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.js
  client/src/components/NavBar.js
  client/src/components/SearchBar.js
  client/src/pages/Searched.js
Labels: fix

#51 allows user to edit information
  client/src/pages/Profile.js
  server/routers/userRouter.js
Labels: enhancement, frontend

#52 advice db
  server/models/adviceModel.js
Labels: backend

#54 Landing page ux
  client/src/pages/Home.js
Labels: frontend

#56 special character error message fix and redirect user after signup
  client/src/App.js
  client/src/components/forms/StepOne.js
  client/src/components/forms/StepTwo.js
  client/src/pages/SuccessfulSignUp.js
Labels: enhancement, frontend, fix
