Repository tenzin1308/Nutrimental, pull requests merged in 2022-03, with the labels that each got.

#59 Justin error fixes
  client/src/components/NavBar.js
  client/src/components/SearchBar.js
  client/src/pages/Home.js
Labels: frontend, fix, cleanup

#58 Tenzin cleanup code
  .github/workflows/node.js.yml
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Account.js
  client/src/components/DevInfo.js
  client/src/components/InfoContainer.js
  client/src/components/NavBar.js
  client/src/components/SearchBar.js
  client/src/components/SearchedItem.js
  client/src/components/forms/StepOne.js
  client/src/components/forms/StepTwo.js
  client/src/components/track/MacroTracker.js
  client/src/pages/Profile.js
  client/src/setupTests.js
  server/models/dailyIntakeModel.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: cleanup

#63 Update to names on AbousUs.js
  client/src/pages/AboutUs.js
Labels: fix

#65 finised about us page + profile page default avatar image
  client/src/assets/profile_pic/FemaleAvatar.jpg
  client/src/assets/profile_pic/MaleAvatar.jpg
  client/src/assets/profile_pic/UnisexAvatar.jpg
  client/src/components/DevInfo.js
  client/src/pages/AboutUs.js
  client/src/pages/Profile.js
Labels: cleanup

#70 Justin macro
  client/package-lock.json
  client/package.json
  client/src/components/AccountLayout.js
  client/src/components/SearchTable.js
  client/src/components/Tabs.js
  client/src/components/track/MacroTracker.js
  client/src/pages/SignIn.js
  client/src/pages/Tracker.js
  server/routers/foodHistoryRouter.js
  server/routers/vitaminRouter.js
Labels: enhancement, frontend, backend

#73 fix: api call adjustment for macro tracker
  client/src/components/track/MacroTracker.js
Labels: API

#75 FoodHistory
  client/src/components/historyTab/FoodHistory.js
  client/src/components/historyTab/Table.js
  client/src/components/historyTab/table.css
  server/routers/foodHistoryRouter.js
Labels: frontend

#79 Dante nutrient advice 2
  client/src/components/AdviceBodyItem.js
  client/src/components/AdviceVitaminItem.js
  client/src/components/VitaminFoodsTable.js
  client/src/components/track/MacroTracker.js
  client/src/components/track/NutrientAdvice.js
  client/src/pages/Tracker.js
  server/models/adviceModel.js
  server/routers/adviceRouter.js
  server/server.js
Labels: enhancement, frontend, cleanup

#90 Update DevInfo.js
  client/src/components/DevInfo.js
Labels: frontend, fix

#95 fix header issue when user makes edit in food history tab
  server/routers/foodHistoryRouter.js
Labels: fix

#93 fixed: user email gets added to food history database
  client/src/components/forms/StepTwo.js
Labels: fix

#96 Users can now use Enter Button as well to search for advice
  client/src/components/track/NutrientAdvice.js
Labels: enhancement, frontend

#94 date fix for food history tracker page
  client/src/components/historyTab/Table.js
Labels: fix

#98 data dictionary for the server
  server/README.md
Labels: documentation

#99 Update StepTwo.js to remove delay
  client/src/components/forms/StepTwo.js
Labels: frontend, cleanup
