Repository tenzin1308/Nutrimental, pull requests merged in 2022-04, with the labels that each got.

#100 fix: Resolved error for when new user signs up
  server/routers/userRouter.js
Labels: fix

#101 multiplied vitamins depending on serving size input along with allowi…
  client/src/components/SearchedItem.js
Labels: enhancement, frontend, fix

#103 transferring nutrient advice to backend
  client/src/components/track/NutrientAdvice.js
  server/routers/adviceRouter.js
Labels: API, backend

#108 user can signup as dietitian
  client/src/components/forms/StepTwo.js
  server/models/userModel.js
Labels: build
